import 'server-only';

import { Pool } from 'pg';

type GlobalWithPg = typeof globalThis & {
  collabDictionaryPool?: Pool;
  collabDictionarySchemaReady?: Promise<void>;
};

const globalForPg = globalThis as GlobalWithPg;

export type WordRow = {
  id: number;
  french: string;
  english: string;
  nufi_json: string[];
  contribution_count: number;
  latest_translation: string | null;
  latest_synonyms: string | null;
};

export type WordComparisonContribution = {
  id: number;
  word_id: number;
  language: string;
  translation: string;
  synonyms: string;
  contributor_name: string;
  notes: string;
  created_at: Date;
};

export type AdminContributionRow = {
  id: number;
  word_id: number;
  french: string;
  english: string;
  nufi_json: string[];
  language: string;
  translation: string;
  synonyms: string;
  contributor_name: string;
  notes: string;
  status: string;
  created_at: Date;
};

export type ComparisonWordRow = {
  id: number;
  french: string;
  english: string;
  nufi_json: string[];
  language_count: number;
  contribution_count: number;
};

function getDatabaseUrl() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error('DATABASE_URL is required. Set it to your Neon pooled PostgreSQL connection string.');
  }
  return databaseUrl;
}

export function getPool() {
  if (!globalForPg.collabDictionaryPool) {
    globalForPg.collabDictionaryPool = new Pool({
      connectionString: getDatabaseUrl(),
      max: 5,
      idleTimeoutMillis: 30_000,
      connectionTimeoutMillis: 10_000,
      ssl: { rejectUnauthorized: false },
    });
  }
  return globalForPg.collabDictionaryPool;
}

export async function ensureSchema() {
  if (!globalForPg.collabDictionarySchemaReady) {
    globalForPg.collabDictionarySchemaReady = getPool().query(`
      CREATE TABLE IF NOT EXISTS predefined_words (
        id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        french          TEXT NOT NULL,
        english         TEXT NOT NULL DEFAULT '',
        nufi_json       JSONB NOT NULL DEFAULT '[]'::jsonb,
        search_text     TEXT NOT NULL DEFAULT '',
        source_row      INTEGER NOT NULL UNIQUE,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS contributions (
        id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        word_id          INTEGER NOT NULL REFERENCES predefined_words(id) ON DELETE CASCADE,
        language         TEXT NOT NULL,
        translation      TEXT NOT NULL,
        synonyms         TEXT NOT NULL DEFAULT '',
        contributor_name TEXT NOT NULL DEFAULT '',
        notes            TEXT NOT NULL DEFAULT '',
        status           TEXT NOT NULL DEFAULT 'approved',
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS admin_users (
        email              TEXT PRIMARY KEY,
        password_hash      TEXT NOT NULL,
        password_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE INDEX IF NOT EXISTS idx_predefined_words_search
        ON predefined_words (search_text);

      CREATE INDEX IF NOT EXISTS idx_contributions_word_language
        ON contributions (word_id, language, created_at DESC);

      CREATE INDEX IF NOT EXISTS idx_contributions_status
        ON contributions (status);
    `).then(() => undefined);
  }

  await globalForPg.collabDictionarySchemaReady;
}

function normalizeLimit(value: number | undefined, fallback: number) {
  return Math.max(1, Math.min(80, value ?? fallback));
}

function normalizeOffset(value: number | undefined) {
  return Math.max(0, value ?? 0);
}

export async function listWords(input: { language: string; q?: string; offset?: number; limit?: number }) {
  await ensureSchema();
  const limit = normalizeLimit(input.limit, 24);
  const offset = normalizeOffset(input.offset);
  const q = input.q?.trim().toLocaleLowerCase() ?? '';
  const searchPattern = q ? `%${q}%` : null;
  const params = searchPattern ? [input.language, searchPattern, limit, offset] : [input.language, limit, offset];
  const where = searchPattern ? `WHERE w.search_text ILIKE $2` : '';
  const limitParam = searchPattern ? '$3' : '$2';
  const offsetParam = searchPattern ? '$4' : '$3';
  const countWhere = q ? `WHERE w.search_text ILIKE $1` : '';

  const pool = getPool();
  const countResult = await pool.query<{ total: string }>(
    `SELECT COUNT(*) AS total FROM predefined_words w ${countWhere}`,
    searchPattern ? [searchPattern] : []
  );
  const rowsResult = await pool.query<WordRow>(
    `
    SELECT
      w.id,
      w.french,
      w.english,
      w.nufi_json,
      (
        SELECT COUNT(*)::int
        FROM contributions c
        WHERE c.word_id = w.id AND c.language = $1 AND c.status = 'approved'
      ) AS contribution_count,
      (
        SELECT c.translation
        FROM contributions c
        WHERE c.word_id = w.id AND c.language = $1 AND c.status = 'approved'
        ORDER BY c.created_at DESC, c.id DESC
        LIMIT 1
      ) AS latest_translation,
      (
        SELECT c.synonyms
        FROM contributions c
        WHERE c.word_id = w.id AND c.language = $1 AND c.status = 'approved'
        ORDER BY c.created_at DESC, c.id DESC
        LIMIT 1
      ) AS latest_synonyms
    FROM predefined_words w
    ${where}
    ORDER BY w.id ASC
    LIMIT ${limitParam} OFFSET ${offsetParam}
  `,
    params
  );

  return { rows: rowsResult.rows, total: Number(countResult.rows[0]?.total ?? 0), limit, offset };
}

export async function listComparisonWords(input: { q?: string; offset?: number; limit?: number }) {
  await ensureSchema();
  const limit = normalizeLimit(input.limit, 20);
  const offset = normalizeOffset(input.offset);
  const q = input.q?.trim().toLocaleLowerCase() ?? '';
  const where = q ? `AND w.search_text ILIKE $1` : '';
  const searchParams = q ? [`%${q}%`] : [];

  const pool = getPool();
  const countResult = await pool.query<{ total: string }>(
    `
    SELECT COUNT(*) AS total
    FROM predefined_words w
    WHERE EXISTS (
      SELECT 1
      FROM contributions c
      WHERE c.word_id = w.id AND c.status = 'approved'
    )
    ${where}
  `,
    searchParams
  );

  const rowsResult = await pool.query<ComparisonWordRow>(
    `
    SELECT
      w.id,
      w.french,
      w.english,
      w.nufi_json,
      COUNT(c.id)::int AS contribution_count,
      COUNT(DISTINCT c.language)::int AS language_count
    FROM predefined_words w
    INNER JOIN contributions c ON c.word_id = w.id AND c.status = 'approved'
    WHERE 1 = 1
      ${where}
    GROUP BY w.id
    ORDER BY language_count DESC, contribution_count DESC, w.id ASC
    LIMIT $${searchParams.length + 1} OFFSET $${searchParams.length + 2}
  `,
    [...searchParams, limit, offset]
  );

  const wordIds = rowsResult.rows.map((row) => row.id);
  const contributionRows =
    wordIds.length > 0
      ? (
          await pool.query<WordComparisonContribution>(
            `
            SELECT id, word_id, language, translation, synonyms, contributor_name, notes, created_at
            FROM contributions
            WHERE word_id = ANY($1::int[])
              AND status = 'approved'
            ORDER BY word_id ASC, language ASC, created_at DESC, id DESC
          `,
            [wordIds]
          )
        ).rows
      : [];

  const contributionsByWordId = new Map<number, WordComparisonContribution[]>();
  for (const contribution of contributionRows) {
    const current = contributionsByWordId.get(contribution.word_id) ?? [];
    current.push(contribution);
    contributionsByWordId.set(contribution.word_id, current);
  }

  return {
    rows: rowsResult.rows,
    total: Number(countResult.rows[0]?.total ?? 0),
    limit,
    offset,
    contributionsByWordId,
  };
}

export async function getWord(wordId: number) {
  await ensureSchema();
  const result = await getPool().query<{
    id: number;
    french: string;
    english: string;
    nufi_json: string[];
  }>(`SELECT id, french, english, nufi_json FROM predefined_words WHERE id = $1 LIMIT 1`, [wordId]);
  return result.rows[0];
}

export async function createContribution(input: {
  wordId: number;
  language: string;
  translation: string;
  synonyms?: string;
  contributorName?: string;
  notes?: string;
}) {
  await ensureSchema();
  const result = await getPool().query<{ id: number }>(
    `
    INSERT INTO contributions (word_id, language, translation, synonyms, contributor_name, notes)
    VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id
  `,
    [
      input.wordId,
      input.language,
      input.translation.trim(),
      input.synonyms?.trim() ?? '',
      input.contributorName?.trim() ?? '',
      input.notes?.trim() ?? '',
    ]
  );

  return result.rows[0].id;
}

export async function listAdminContributions(input: { q?: string; offset?: number; limit?: number }) {
  await ensureSchema();
  const limit = normalizeLimit(input.limit, 50);
  const offset = normalizeOffset(input.offset);
  const q = input.q?.trim() ?? '';
  const searchPattern = q ? `%${q}%` : null;
  const where = searchPattern
    ? `WHERE w.search_text ILIKE $1
        OR c.language ILIKE $1
        OR c.translation ILIKE $1
        OR c.synonyms ILIKE $1
        OR c.contributor_name ILIKE $1`
    : '';
  const params = searchPattern ? [searchPattern, limit, offset] : [limit, offset];
  const limitParam = searchPattern ? '$2' : '$1';
  const offsetParam = searchPattern ? '$3' : '$2';

  const countResult = await getPool().query<{ total: string }>(
    `
    SELECT COUNT(*) AS total
    FROM contributions c
    INNER JOIN predefined_words w ON w.id = c.word_id
    ${where}
  `,
    searchPattern ? [searchPattern] : []
  );
  const rowsResult = await getPool().query<AdminContributionRow>(
    `
    SELECT
      c.id,
      c.word_id,
      w.french,
      w.english,
      w.nufi_json,
      c.language,
      c.translation,
      c.synonyms,
      c.contributor_name,
      c.notes,
      c.status,
      c.created_at
    FROM contributions c
    INNER JOIN predefined_words w ON w.id = c.word_id
    ${where}
    ORDER BY c.created_at DESC, c.id DESC
    LIMIT ${limitParam} OFFSET ${offsetParam}
  `,
    params
  );

  return { rows: rowsResult.rows, total: Number(countResult.rows[0]?.total ?? 0), limit, offset };
}

export async function updateAdminContribution(input: {
  id: number;
  language: string;
  translation: string;
  synonyms: string;
  contributorName: string;
  notes: string;
  status: string;
}) {
  await ensureSchema();
  const result = await getPool().query<{ id: number }>(
    `
    UPDATE contributions
    SET language = $2,
        translation = $3,
        synonyms = $4,
        contributor_name = $5,
        notes = $6,
        status = $7
    WHERE id = $1
    RETURNING id
  `,
    [
      input.id,
      input.language.trim(),
      input.translation.trim(),
      input.synonyms.trim(),
      input.contributorName.trim(),
      input.notes.trim(),
      input.status.trim(),
    ]
  );
  return result.rows[0] ?? null;
}

export async function deleteAdminContribution(id: number) {
  await ensureSchema();
  const result = await getPool().query(`DELETE FROM contributions WHERE id = $1`, [id]);
  return (result.rowCount ?? 0) > 0;
}

export async function getAdminPasswordHash(email: string) {
  await ensureSchema();
  const result = await getPool().query<{ password_hash: string }>(
    `SELECT password_hash FROM admin_users WHERE email = $1 LIMIT 1`,
    [email.trim().toLowerCase()]
  );
  return result.rows[0]?.password_hash ?? null;
}

export async function setAdminPasswordHash(email: string, passwordHash: string) {
  await ensureSchema();
  await getPool().query(
    `
    INSERT INTO admin_users (email, password_hash)
    VALUES ($1, $2)
    ON CONFLICT (email)
    DO UPDATE SET password_hash = EXCLUDED.password_hash,
                  password_updated_at = now()
  `,
    [email.trim().toLowerCase(), passwordHash]
  );
}
