import 'server-only';

import { Pool } from 'pg';
import { LANGUAGES } from '@/lib/languages';

type GlobalWithPg = typeof globalThis & {
  collabDictionaryPool?: Pool;
  collabDictionarySchemaReady?: Promise<void>;
};

const globalForPg = globalThis as GlobalWithPg;

export type WordRow = {
  id: number;
  french: string;
  english: string;
  nufi_json: string[];
  contribution_count: number;
  latest_translation: string | null;
  latest_synonyms: string | null;
};

export type WordComparisonContribution = {
  id: number;
  word_id: number;
  language: string;
  translation: string;
  synonyms: string;
  contributor_name: string;
  contributor_email: string;
  notes: string;
  status: string;
  created_at: Date;
};

export type AdminContributionRow = {
  id: number;
  word_id: number;
  french: string;
  english: string;
  nufi_json: string[];
  language: string;
  translation: string;
  synonyms: string;
  contributor_name: string;
  contributor_email: string;
  notes: string;
  status: string;
  created_at: Date;
};

export type AdminWordRow = {
  word_id: number;
  french: string;
  english: string;
  nufi_json: string[];
  contribution_id: number | null;
  language: string | null;
  translation: string | null;
  synonyms: string | null;
  contributor_name: string | null;
  contributor_email: string | null;
  notes: string | null;
  status: string | null;
  created_at: Date | null;
};

export type ComparisonWordRow = {
  id: number;
  french: string;
  english: string;
  nufi_json: string[];
  language_count: number;
  contribution_count: number;
};

export type GameTranslationClue = {
  language: string;
  translation: string;
};

function getDatabaseUrl() {
  const databaseUrl = process.env.DATABASE_URL;
  if (!databaseUrl) {
    throw new Error('DATABASE_URL is required. Set it to your Neon pooled PostgreSQL connection string.');
  }
  return databaseUrl;
}

export function getPool() {
  if (!globalForPg.collabDictionaryPool) {
    globalForPg.collabDictionaryPool = new Pool({
      connectionString: getDatabaseUrl(),
      max: 5,
      idleTimeoutMillis: 30_000,
      connectionTimeoutMillis: 10_000,
      ssl: { rejectUnauthorized: false },
    });
  }
  return globalForPg.collabDictionaryPool;
}

export async function ensureSchema() {
  if (!globalForPg.collabDictionarySchemaReady) {
    globalForPg.collabDictionarySchemaReady = getPool().query(`
      CREATE TABLE IF NOT EXISTS predefined_words (
        id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        french          TEXT NOT NULL,
        english         TEXT NOT NULL DEFAULT '',
        nufi_json       JSONB NOT NULL DEFAULT '[]'::jsonb,
        search_text     TEXT NOT NULL DEFAULT '',
        source_row      INTEGER NOT NULL,
        import_key      TEXT,
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      ALTER TABLE predefined_words DROP CONSTRAINT IF EXISTS predefined_words_source_row_key;
      ALTER TABLE predefined_words ADD COLUMN IF NOT EXISTS import_key TEXT;

      CREATE TABLE IF NOT EXISTS contributions (
        id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        word_id          INTEGER NOT NULL REFERENCES predefined_words(id) ON DELETE CASCADE,
        language         TEXT NOT NULL,
        translation      TEXT NOT NULL,
        synonyms         TEXT NOT NULL DEFAULT '',
        contributor_name TEXT NOT NULL DEFAULT '',
        contributor_email TEXT NOT NULL DEFAULT '',
        notes            TEXT NOT NULL DEFAULT '',
        status           TEXT NOT NULL DEFAULT 'pending',
        created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      ALTER TABLE contributions ADD COLUMN IF NOT EXISTS contributor_email TEXT NOT NULL DEFAULT '';
      ALTER TABLE contributions ALTER COLUMN status SET DEFAULT 'pending';

      CREATE TABLE IF NOT EXISTS game_scores (
        id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        game_id            TEXT NOT NULL,
        player_key         TEXT NOT NULL,
        player_name        TEXT NOT NULL DEFAULT '',
        player_email       TEXT NOT NULL DEFAULT '',
        word_id            INTEGER REFERENCES predefined_words(id) ON DELETE SET NULL,
        preferred_language TEXT NOT NULL,
        selected_answer    TEXT NOT NULL DEFAULT '',
        correct_answer     TEXT NOT NULL DEFAULT '',
        is_correct         BOOLEAN NOT NULL,
        streak             INTEGER NOT NULL DEFAULT 0,
        created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE TABLE IF NOT EXISTS translation_cache (
        id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        source_language TEXT NOT NULL,
        target_language TEXT NOT NULL,
        source_text     TEXT NOT NULL,
        translated_text TEXT NOT NULL,
        provider        TEXT NOT NULL DEFAULT '',
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (source_language, target_language, source_text)
      );

      CREATE TABLE IF NOT EXISTS admin_users (
        email              TEXT PRIMARY KEY,
        password_hash      TEXT NOT NULL,
        password_updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
      );

      CREATE INDEX IF NOT EXISTS idx_predefined_words_search
        ON predefined_words (search_text);

      CREATE INDEX IF NOT EXISTS idx_predefined_words_source_row
        ON predefined_words (source_row);

      CREATE UNIQUE INDEX IF NOT EXISTS idx_predefined_words_import_key
        ON predefined_words (import_key)
        WHERE import_key IS NOT NULL;

      CREATE UNIQUE INDEX IF NOT EXISTS idx_predefined_words_french_unique
        ON predefined_words (lower(french));

      CREATE INDEX IF NOT EXISTS idx_contributions_word_language
        ON contributions (word_id, language, created_at DESC);

      CREATE INDEX IF NOT EXISTS idx_contributions_status
        ON contributions (status);

      CREATE INDEX IF NOT EXISTS idx_contributions_contributor_email
        ON contributions (contributor_email);

      CREATE INDEX IF NOT EXISTS idx_game_scores_player
        ON game_scores (game_id, player_key, created_at DESC);

      CREATE INDEX IF NOT EXISTS idx_game_scores_created_at
        ON game_scores (created_at DESC);

      CREATE INDEX IF NOT EXISTS idx_translation_cache_lookup
        ON translation_cache (source_language, target_language, source_text);
    `).then(() => undefined);
  }

  await globalForPg.collabDictionarySchemaReady;
}

function normalizeLimit(value: number | undefined, fallback: number) {
  return Math.max(1, Math.min(80, value ?? fallback));
}

function normalizeOffset(value: number | undefined) {
  return Math.max(0, value ?? 0);
}

function isNumberLikeAnswer(value: string) {
  return /^[+-]?\d+(?:[.,]\d+)?$/.test(value.trim());
}

function normalizeAnswer(value: string) {
  return value.replace(/\s+/g, ' ').trim();
}

async function translateFrenchToEnglish(sourceText: string) {
  const normalizedSource = normalizeAnswer(sourceText);
  if (!normalizedSource || isNumberLikeAnswer(normalizedSource)) return normalizedSource;

  const pool = getPool();
  const cached = await pool.query<{ translated_text: string }>(
    `
    SELECT translated_text
    FROM translation_cache
    WHERE source_language = 'fr'
      AND target_language = 'en'
      AND source_text = $1
    LIMIT 1
    `,
    [normalizedSource]
  );

  const cachedText = normalizeAnswer(cached.rows[0]?.translated_text ?? '');
  if (cachedText) return cachedText;

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 6000);
  let translatedText = '';
  try {
    const url = new URL('https://api.mymemory.translated.net/get');
    url.searchParams.set('q', normalizedSource);
    url.searchParams.set('langpair', 'fr|en');
    const response = await fetch(url, { signal: controller.signal, cache: 'no-store' });
    const payload = (await response.json().catch(() => null)) as { responseData?: { translatedText?: string } } | null;
    translatedText = normalizeAnswer(payload?.responseData?.translatedText ?? '');
  } catch {
    translatedText = '';
  } finally {
    clearTimeout(timeout);
  }

  const finalText = translatedText || normalizedSource;
  await pool
    .query(
      `
      INSERT INTO translation_cache (source_language, target_language, source_text, translated_text, provider, updated_at)
      VALUES ('fr', 'en', $1, $2, $3, now())
      ON CONFLICT (source_language, target_language, source_text)
      DO UPDATE SET
        translated_text = EXCLUDED.translated_text,
        provider = EXCLUDED.provider,
        updated_at = now()
      `,
      [normalizedSource, finalText, translatedText ? 'mymemory' : 'fallback']
    )
    .catch(() => undefined);

  return finalText;
}

export async function listWords(input: { language: string; q?: string; offset?: number; limit?: number }) {
  await ensureSchema();
  const limit = normalizeLimit(input.limit, 24);
  const offset = normalizeOffset(input.offset);
  const q = input.q?.trim().toLocaleLowerCase() ?? '';
  const searchPattern = q ? `%${q}%` : null;
  const params = searchPattern ? [input.language, searchPattern, limit, offset] : [input.language, limit, offset];
  const where = searchPattern ? `WHERE w.search_text ILIKE $2` : '';
  const limitParam = searchPattern ? '$3' : '$2';
  const offsetParam = searchPattern ? '$4' : '$3';
  const countWhere = q ? `WHERE w.search_text ILIKE $1` : '';

  const pool = getPool();
  const countResult = await pool.query<{ total: string }>(
    `SELECT COUNT(*) AS total FROM predefined_words w ${countWhere}`,
    searchPattern ? [searchPattern] : []
  );
  const rowsResult = await pool.query<WordRow>(
    `
    SELECT
      w.id,
      w.french,
      w.english,
      w.nufi_json,
      COALESCE(stats.contribution_count, 0)::int AS contribution_count,
      latest.translation AS latest_translation,
      latest.synonyms AS latest_synonyms
    FROM predefined_words w
    LEFT JOIN LATERAL (
      SELECT COUNT(*)::int AS contribution_count
      FROM contributions c
      WHERE c.word_id = w.id
        AND c.language = $1
        AND c.status <> 'rejected'
    ) stats ON true
    LEFT JOIN LATERAL (
      SELECT c.translation, c.synonyms
      FROM contributions c
      WHERE c.word_id = w.id
        AND c.language = $1
        AND c.status <> 'rejected'
      ORDER BY c.created_at DESC, c.id DESC
      LIMIT 1
    ) latest ON true
    ${where}
    ORDER BY
      CASE WHEN COALESCE(stats.contribution_count, 0) = 0 THEN 0 ELSE 1 END,
      w.source_row ASC,
      w.id ASC
    LIMIT ${limitParam} OFFSET ${offsetParam}
  `,
    params
  );

  return { rows: rowsResult.rows, total: Number(countResult.rows[0]?.total ?? 0), limit, offset };
}

export async function getRandomWord(input: { language: string; excludeId?: number | null }) {
  await ensureSchema();

  const pool = getPool();
  const countResult = await pool.query<{ total: string }>(`SELECT COUNT(*) AS total FROM predefined_words`);
  const rowsResult = await pool.query<WordRow>(
    `
    SELECT
      w.id,
      w.french,
      w.english,
      w.nufi_json,
      COALESCE(stats.contribution_count, 0)::int AS contribution_count,
      latest.translation AS latest_translation,
      latest.synonyms AS latest_synonyms
    FROM predefined_words w
    LEFT JOIN LATERAL (
      SELECT COUNT(*)::int AS contribution_count
      FROM contributions c
      WHERE c.word_id = w.id
        AND c.language = $1
        AND c.status <> 'rejected'
    ) stats ON true
    LEFT JOIN LATERAL (
      SELECT c.translation, c.synonyms
      FROM contributions c
      WHERE c.word_id = w.id
        AND c.language = $1
        AND c.status <> 'rejected'
      ORDER BY c.created_at DESC, c.id DESC
      LIMIT 1
    ) latest ON true
    WHERE ($2::int IS NULL OR w.id <> $2)
    ORDER BY
      CASE WHEN COALESCE(stats.contribution_count, 0) = 0 THEN 0 ELSE 1 END,
      random()
    LIMIT 1
  `,
    [input.language, input.excludeId ?? null]
  );

  return { rows: rowsResult.rows, total: Number(countResult.rows[0]?.total ?? 0), limit: 1, offset: 0 };
}

export async function getWordMatchRound(input: {
  excludedLanguages?: string[];
  preferredLanguage: 'english' | 'french';
  excludeId?: number | null;
  previousLanguage?: string | null;
}) {
  await ensureSchema();

  const excludedLanguages = [...new Set(input.excludedLanguages ?? [])].filter(Boolean);
  const pool = getPool();
  const answerLanguage = input.preferredLanguage;

  const answerColumn = 'french';
  const answerFilter = `AND trim(w.french) <> ''`;

  const wordResult = await pool.query<{
    id: number;
    french: string;
    english: string;
    contribution_clues: GameTranslationClue[] | null;
  }>(
    `
    WITH latest_contributions AS (
      SELECT DISTINCT ON (word_id, language)
        word_id,
        language,
        translation
      FROM contributions
      WHERE status <> 'rejected'
        AND trim(translation) <> ''
        AND NOT (language = ANY($1::text[]))
        AND language = ANY($4::text[])
      ORDER BY word_id, language, created_at DESC, id DESC
    ),
    candidate_clues AS (
      SELECT
        w.id AS word_id,
        'nufi'::text AS language,
        nufi_value.translation
      FROM predefined_words w
      CROSS JOIN LATERAL jsonb_array_elements_text(w.nufi_json) AS nufi_value(translation)
      WHERE 'nufi' <> ALL($1::text[])
        AND trim(nufi_value.translation) <> ''
        AND trim(w.${answerColumn}) <> ''
        ${answerFilter}

      UNION ALL

      SELECT
        w.id AS word_id,
        lc.language,
        lc.translation
      FROM predefined_words w
      INNER JOIN latest_contributions lc ON lc.word_id = w.id
      WHERE trim(w.${answerColumn}) <> ''
        ${answerFilter}
    ),
    available_languages AS (
      SELECT DISTINCT language
      FROM candidate_clues
    ),
    selected_language AS (
      SELECT language
      FROM available_languages
      WHERE (
        $3::text IS NULL
        OR language <> $3
        OR (SELECT COUNT(*) FROM available_languages) = 1
      )
      ORDER BY random()
      LIMIT 1
    ),
    selected_word AS (
      SELECT
        w.id,
        w.french,
        w.english
      FROM candidate_clues clue
      INNER JOIN selected_language selected ON selected.language = clue.language
      INNER JOIN predefined_words w ON w.id = clue.word_id
      WHERE ($2::int IS NULL OR w.id <> $2)
      ORDER BY random()
      LIMIT 1
    )
    SELECT
      selected_word.id,
      selected_word.french,
      selected_word.english,
      COALESCE(
        jsonb_agg(
          jsonb_build_object('language', clue.language, 'translation', clue.translation)
          ORDER BY
            CASE WHEN clue.language = selected_language.language THEN 0 ELSE 1 END,
            random()
        ) FILTER (WHERE clue.translation IS NOT NULL),
        '[]'::jsonb
      ) AS contribution_clues
    FROM selected_word
    CROSS JOIN selected_language
    INNER JOIN candidate_clues clue ON clue.word_id = selected_word.id
    GROUP BY selected_word.id, selected_word.french, selected_word.english
  `,
    [
      excludedLanguages,
      input.excludeId ?? null,
      input.previousLanguage ?? null,
      LANGUAGES.filter((language) => language.id !== 'other').map((language) => language.id),
    ]
  );

  const word = wordResult.rows[0];
  if (!word) return null;

  const clues: GameTranslationClue[] = [];
  for (const clue of word.contribution_clues ?? []) {
    const translation = String(clue.translation ?? '').trim();
    if (translation) clues.push({ language: clue.language, translation });
  }

  const choicesResult = await pool.query<{ answer: string }>(
    `
    SELECT answer
    FROM (
      SELECT DISTINCT w.${answerColumn} AS answer
      FROM predefined_words w
      WHERE trim(w.${answerColumn}) <> ''
        ${answerFilter}
        AND w.id <> $1
    ) answers
    ORDER BY random()
    LIMIT 120
  `,
    [word.id]
  );

  const correctSourceAnswer = word.french;
  const correctAnswer = answerLanguage === 'english' ? await translateFrenchToEnglish(correctSourceAnswer) : correctSourceAnswer;
  const correctAnswerIsNumber = isNumberLikeAnswer(correctSourceAnswer);
  const choices = [correctAnswer];
  for (const row of choicesResult.rows) {
    const sourceAnswer = normalizeAnswer(row.answer);
    const answer = answerLanguage === 'english' ? await translateFrenchToEnglish(sourceAnswer) : sourceAnswer;
    if (
      answer &&
      isNumberLikeAnswer(sourceAnswer) === correctAnswerIsNumber &&
      !choices.some((choice) => choice.toLocaleLowerCase() === answer.toLocaleLowerCase())
    ) {
      choices.push(answer);
    }
    if (choices.length >= 4) break;
  }

  return {
    id: word.id,
    french: word.french,
    english: word.english,
    clues,
    correctAnswer,
    choices,
    answerLanguage,
  };
}

export async function listPlayableGameLanguages() {
  await ensureSchema();

  const publicLanguageIds = LANGUAGES.filter((language) => language.id !== 'other').map((language) => language.id);
  const result = await getPool().query<{ language: string; word_count: number }>(
    `
    WITH nufi_words AS (
      SELECT DISTINCT 'nufi'::text AS language, w.id AS word_id
      FROM predefined_words w
      WHERE jsonb_array_length(w.nufi_json) > 0
        AND trim(w.french) <> ''
    ),
    contribution_words AS (
      SELECT DISTINCT c.language, c.word_id
      FROM contributions c
      INNER JOIN predefined_words w ON w.id = c.word_id
      WHERE c.status <> 'rejected'
        AND trim(c.translation) <> ''
        AND trim(w.french) <> ''
        AND c.language = ANY($1::text[])
    )
    SELECT language, COUNT(DISTINCT word_id)::int AS word_count
    FROM (
      SELECT * FROM nufi_words
      UNION ALL
      SELECT * FROM contribution_words
    ) playable
    GROUP BY language
    ORDER BY language ASC
  `,
    [publicLanguageIds]
  );

  return result.rows;
}

export async function listComparisonWords(input: { q?: string; offset?: number; limit?: number }) {
  await ensureSchema();
  const limit = normalizeLimit(input.limit, 20);
  const offset = normalizeOffset(input.offset);
  const q = input.q?.trim().toLocaleLowerCase() ?? '';
  const where = q
    ? `AND (
        w.search_text ILIKE $1
        OR EXISTS (
          SELECT 1
          FROM contributions search_c
          WHERE search_c.word_id = w.id
            AND search_c.status <> 'rejected'
            AND (
              search_c.language ILIKE $1
              OR search_c.translation ILIKE $1
              OR search_c.synonyms ILIKE $1
              OR search_c.contributor_name ILIKE $1
            )
        )
      )`
    : '';
  const searchParams = q ? [`%${q}%`] : [];

  const pool = getPool();
  const countResult = await pool.query<{ total: string }>(
    `
    SELECT COUNT(*) AS total
    FROM predefined_words w
    WHERE EXISTS (
      SELECT 1
      FROM contributions c
      WHERE c.word_id = w.id AND c.status <> 'rejected'
    )
    ${where}
  `,
    searchParams
  );

  const rowsResult = await pool.query<ComparisonWordRow>(
    `
    SELECT
      w.id,
      w.french,
      w.english,
      w.nufi_json,
      COUNT(c.id)::int AS contribution_count,
      COUNT(DISTINCT c.language)::int AS language_count
    FROM predefined_words w
    INNER JOIN contributions c ON c.word_id = w.id AND c.status <> 'rejected'
    WHERE 1 = 1
      ${where}
    GROUP BY w.id
    ORDER BY language_count DESC, contribution_count DESC, w.id ASC
    LIMIT $${searchParams.length + 1} OFFSET $${searchParams.length + 2}
  `,
    [...searchParams, limit, offset]
  );

  const wordIds = rowsResult.rows.map((row) => row.id);
  const contributionRows =
    wordIds.length > 0
      ? (
          await pool.query<WordComparisonContribution>(
            `
            SELECT id, word_id, language, translation, synonyms, contributor_name, contributor_email, notes, status, created_at
            FROM contributions
            WHERE word_id = ANY($1::int[])
              AND status <> 'rejected'
            ORDER BY word_id ASC, language ASC, created_at DESC, id DESC
          `,
            [wordIds]
          )
        ).rows
      : [];

  const contributionsByWordId = new Map<number, WordComparisonContribution[]>();
  for (const contribution of contributionRows) {
    const current = contributionsByWordId.get(contribution.word_id) ?? [];
    current.push(contribution);
    contributionsByWordId.set(contribution.word_id, current);
  }

  return {
    rows: rowsResult.rows,
    total: Number(countResult.rows[0]?.total ?? 0),
    limit,
    offset,
    contributionsByWordId,
  };
}

export async function getWord(wordId: number) {
  await ensureSchema();
  const result = await getPool().query<{
    id: number;
    french: string;
    english: string;
    nufi_json: string[];
  }>(`SELECT id, french, english, nufi_json FROM predefined_words WHERE id = $1 LIMIT 1`, [wordId]);
  return result.rows[0];
}

export async function createContribution(input: {
  wordId: number;
  language: string;
  translation: string;
  synonyms?: string;
  contributorName?: string;
  contributorEmail?: string;
  notes?: string;
}) {
  await ensureSchema();
  const contributorEmail = input.contributorEmail?.trim().toLowerCase() ?? '';

  if (contributorEmail) {
    const existing = await getPool().query<{ id: number }>(
      `
      SELECT id
      FROM contributions
      WHERE word_id = $1
        AND language = $2
        AND contributor_email = $3
      ORDER BY created_at DESC, id DESC
      LIMIT 1
    `,
      [input.wordId, input.language, contributorEmail]
    );

    const existingId = existing.rows[0]?.id;
    if (existingId) {
      const updated = await getPool().query<{ id: number }>(
        `
        UPDATE contributions
        SET translation = $2,
            synonyms = $3,
            contributor_name = $4,
            notes = $5,
            status = 'pending',
            created_at = now()
        WHERE id = $1
        RETURNING id
      `,
        [
          existingId,
          input.translation.trim(),
          input.synonyms?.trim() ?? '',
          input.contributorName?.trim() ?? '',
          input.notes?.trim() ?? '',
        ]
      );

      return updated.rows[0].id;
    }
  }

  const result = await getPool().query<{ id: number }>(
    `
    INSERT INTO contributions (word_id, language, translation, synonyms, contributor_name, contributor_email, notes, status)
    VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending')
    RETURNING id
  `,
    [
      input.wordId,
      input.language,
      input.translation.trim(),
      input.synonyms?.trim() ?? '',
      input.contributorName?.trim() ?? '',
      contributorEmail,
      input.notes?.trim() ?? '',
    ]
  );

  return result.rows[0].id;
}

export async function getContributorStats(email: string) {
  await ensureSchema();
  const normalizedEmail = email.trim().toLowerCase();
  if (!normalizedEmail) return { contributionCount: 0, points: 0, rank: null, rankedContributorCount: 0 };

  const result = await getPool().query<{
    contribution_count: string;
    rank: string | null;
    ranked_contributor_count: string;
  }>(
    `
    WITH latest_contributions AS (
      SELECT DISTINCT ON (contributor_email, word_id, language)
        contributor_email,
        status
      FROM contributions
      WHERE contributor_email <> ''
      ORDER BY contributor_email, word_id, language, created_at DESC, id DESC
    ),
    contributor_scores AS (
      SELECT
        contributor_email,
        COUNT(*) FILTER (WHERE status <> 'rejected')::int AS contribution_count
      FROM latest_contributions
      GROUP BY contributor_email
      HAVING COUNT(*) FILTER (WHERE status <> 'rejected') > 0
    ),
    ranked_scores AS (
      SELECT
        contributor_email,
        contribution_count,
        DENSE_RANK() OVER (ORDER BY contribution_count DESC) AS rank,
        COUNT(*) OVER () AS ranked_contributor_count
      FROM contributor_scores
    )
    SELECT
      COALESCE(contribution_count, 0)::text AS contribution_count,
      rank::text AS rank,
      COALESCE(ranked_contributor_count, (SELECT COUNT(*) FROM contributor_scores), 0)::text AS ranked_contributor_count
    FROM ranked_scores
    WHERE contributor_email = $1
  `,
    [normalizedEmail]
  );
  const row = result.rows[0];
  const totalResult = row
    ? null
    : await getPool().query<{ total: string }>(`
        WITH latest_contributions AS (
          SELECT DISTINCT ON (contributor_email, word_id, language) contributor_email, status
          FROM contributions
          WHERE contributor_email <> ''
          ORDER BY contributor_email, word_id, language, created_at DESC, id DESC
        )
        SELECT COUNT(DISTINCT contributor_email)::text AS total
        FROM latest_contributions
        WHERE status <> 'rejected'
      `);
  const contributionCount = Number(row?.contribution_count ?? 0);
  return {
    contributionCount,
    points: contributionCount * 50,
    rank: row?.rank ? Number(row.rank) : null,
    rankedContributorCount: Number(row?.ranked_contributor_count ?? totalResult?.rows[0]?.total ?? 0),
  };
}

export type ContributorLeaderboardRow = {
  contributor_email: string;
  contributor_name: string;
  contribution_count: number;
  approved_count: number;
  pending_count: number;
  language_count: number;
  languages: string[];
  latest_contribution_at: Date;
  rank: number;
  ranked_contributor_count: number;
};

export type GamerLeaderboardRow = {
  player_key: string;
  player_name: string;
  player_email: string;
  round_count: number;
  correct_count: number;
  best_streak: number;
  latest_played_at: Date;
  rank: number;
  ranked_player_count: number;
};

export async function listContributorLeaderboard(limit = 100) {
  await ensureSchema();

  const result = await getPool().query<ContributorLeaderboardRow>(
    `
    WITH latest_contributions AS (
      SELECT DISTINCT ON (contributor_email, word_id, language)
        contributor_email,
        language,
        status,
        created_at,
        id
      FROM contributions
      WHERE contributor_email <> ''
      ORDER BY contributor_email, word_id, language, created_at DESC, id DESC
    ),
    valid_contributions AS (
      SELECT *
      FROM latest_contributions
      WHERE status <> 'rejected'
    ),
    latest_names AS (
      SELECT DISTINCT ON (contributor_email)
        contributor_email,
        contributor_name
      FROM contributions
      WHERE contributor_email <> ''
        AND contributor_name <> ''
      ORDER BY contributor_email, created_at DESC, id DESC
    ),
    contributor_scores AS (
      SELECT
        valid_contributions.contributor_email,
        COALESCE(latest_names.contributor_name, '') AS contributor_name,
        COUNT(*)::int AS contribution_count,
        COUNT(*) FILTER (WHERE valid_contributions.status = 'approved')::int AS approved_count,
        COUNT(*) FILTER (WHERE valid_contributions.status = 'pending')::int AS pending_count,
        COUNT(DISTINCT valid_contributions.language)::int AS language_count,
        ARRAY_AGG(DISTINCT valid_contributions.language ORDER BY valid_contributions.language) AS languages,
        MAX(valid_contributions.created_at) AS latest_contribution_at
      FROM valid_contributions
      LEFT JOIN latest_names ON latest_names.contributor_email = valid_contributions.contributor_email
      GROUP BY valid_contributions.contributor_email, latest_names.contributor_name
    ),
    ranked_scores AS (
      SELECT
        *,
        DENSE_RANK() OVER (ORDER BY contribution_count DESC) AS rank,
        COUNT(*) OVER () AS ranked_contributor_count
      FROM contributor_scores
    )
    SELECT
      contributor_email,
      contributor_name,
      contribution_count,
      approved_count,
      pending_count,
      language_count,
      languages,
      latest_contribution_at,
      rank::int,
      ranked_contributor_count::int
    FROM ranked_scores
    ORDER BY rank ASC, latest_contribution_at DESC, contributor_email ASC
    LIMIT $1
  `,
    [Math.max(1, Math.min(limit, 250))]
  );

  return result.rows;
}

function normalizePlayerKey(input: { playerName?: string; playerEmail?: string; playerId?: string }) {
  const email = input.playerEmail?.trim().toLowerCase() ?? '';
  if (email) return email;

  const playerId = input.playerId?.trim() ?? '';
  if (playerId) return `local:${playerId.slice(0, 120)}`;

  return (input.playerName?.trim().toLowerCase() || 'anonymous')
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9._-]+/g, '')
    .slice(0, 100);
}

export async function recordGameScore(input: {
  gameId: string;
  playerId?: string;
  playerName?: string;
  playerEmail?: string;
  wordId: number;
  preferredLanguage: 'english' | 'french';
  selectedAnswer: string;
  correctAnswer: string;
  isCorrect: boolean;
  streak: number;
}) {
  await ensureSchema();

  const playerName = input.playerName?.trim().slice(0, 120) ?? '';
  const playerEmail = input.playerEmail?.trim().toLowerCase().slice(0, 160) ?? '';
  const playerKey = normalizePlayerKey({ playerName, playerEmail, playerId: input.playerId });

  const result = await getPool().query<{ id: number }>(
    `
    INSERT INTO game_scores (
      game_id,
      player_key,
      player_name,
      player_email,
      word_id,
      preferred_language,
      selected_answer,
      correct_answer,
      is_correct,
      streak
    )
    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
    RETURNING id
  `,
    [
      input.gameId,
      playerKey,
      playerName,
      playerEmail,
      input.wordId,
      input.preferredLanguage,
      input.selectedAnswer.trim(),
      input.correctAnswer.trim(),
      input.isCorrect,
      Math.max(0, input.streak),
    ]
  );

  return result.rows[0]?.id ?? null;
}

export async function listGamerLeaderboard(limit = 100) {
  await ensureSchema();

  const result = await getPool().query<GamerLeaderboardRow>(
    `
    WITH latest_names AS (
      SELECT DISTINCT ON (player_key)
        player_key,
        player_name,
        player_email
      FROM game_scores
      ORDER BY player_key, created_at DESC, id DESC
    ),
    player_scores AS (
      SELECT
        game_scores.player_key,
        COALESCE(latest_names.player_name, '') AS player_name,
        COALESCE(latest_names.player_email, '') AS player_email,
        COUNT(*)::int AS round_count,
        COUNT(*) FILTER (WHERE is_correct)::int AS correct_count,
        COALESCE(MAX(streak), 0)::int AS best_streak,
        MAX(created_at) AS latest_played_at
      FROM game_scores
      LEFT JOIN latest_names ON latest_names.player_key = game_scores.player_key
      WHERE game_id = 'word-match'
      GROUP BY game_scores.player_key, latest_names.player_name, latest_names.player_email
    ),
    ranked_scores AS (
      SELECT
        *,
        DENSE_RANK() OVER (ORDER BY correct_count DESC, best_streak DESC, round_count ASC, latest_played_at ASC) AS rank,
        COUNT(*) OVER () AS ranked_player_count
      FROM player_scores
    )
    SELECT
      player_key,
      player_name,
      player_email,
      round_count,
      correct_count,
      best_streak,
      latest_played_at,
      rank::int,
      ranked_player_count::int
    FROM ranked_scores
    ORDER BY rank ASC, latest_played_at DESC, player_key ASC
    LIMIT $1
  `,
    [Math.max(1, Math.min(limit, 250))]
  );

  return result.rows;
}

export type ContributorContributionExportRow = {
  created_at: Date;
  status: string;
  language: string;
  french: string;
  english: string;
  nufi_json: string[];
  translation: string;
  synonyms: string;
  notes: string;
  contributor_name: string;
  contributor_email: string;
};

export async function listContributorContributionsForExport(email: string) {
  await ensureSchema();
  const normalizedEmail = email.trim().toLowerCase();
  if (!normalizedEmail) return [];

  const result = await getPool().query<ContributorContributionExportRow>(
    `
    SELECT
      c.created_at,
      c.status,
      c.language,
      w.french,
      w.english,
      w.nufi_json,
      c.translation,
      c.synonyms,
      c.notes,
      c.contributor_name,
      c.contributor_email
    FROM contributions c
    INNER JOIN predefined_words w ON w.id = c.word_id
    WHERE c.contributor_email = $1
    ORDER BY c.created_at DESC, c.id DESC
  `,
    [normalizedEmail]
  );

  return result.rows;
}

export async function listAdminContributions(input: { q?: string; offset?: number; limit?: number }) {
  await ensureSchema();
  const limit = normalizeLimit(input.limit, 50);
  const offset = normalizeOffset(input.offset);
  const q = input.q?.trim() ?? '';
  const searchPattern = q ? `%${q}%` : null;
  const where = searchPattern
    ? `WHERE w.search_text ILIKE $1
        OR c.language ILIKE $1
        OR c.translation ILIKE $1
        OR c.synonyms ILIKE $1
        OR c.contributor_name ILIKE $1
        OR c.contributor_email ILIKE $1`
    : '';
  const params = searchPattern ? [searchPattern, limit, offset] : [limit, offset];
  const limitParam = searchPattern ? '$2' : '$1';
  const offsetParam = searchPattern ? '$3' : '$2';

  const countResult = await getPool().query<{ total: string }>(
    `
    SELECT COUNT(*) AS total
    FROM contributions c
    INNER JOIN predefined_words w ON w.id = c.word_id
    ${where}
  `,
    searchPattern ? [searchPattern] : []
  );
  const rowsResult = await getPool().query<AdminContributionRow>(
    `
    SELECT
      c.id,
      c.word_id,
      w.french,
      w.english,
      w.nufi_json,
      c.language,
      c.translation,
      c.synonyms,
      c.contributor_name,
      c.contributor_email,
      c.notes,
      c.status,
      c.created_at
    FROM contributions c
    INNER JOIN predefined_words w ON w.id = c.word_id
    ${where}
    ORDER BY c.created_at DESC, c.id DESC
    LIMIT ${limitParam} OFFSET ${offsetParam}
  `,
    params
  );

  return { rows: rowsResult.rows, total: Number(countResult.rows[0]?.total ?? 0), limit, offset };
}

export async function listAdminWords(input: { language: string; q?: string; offset?: number; limit?: number }) {
  await ensureSchema();
  const limit = normalizeLimit(input.limit, 50);
  const offset = normalizeOffset(input.offset);
  const language = input.language.trim();
  const q = input.q?.trim() ?? '';
  const searchPattern = q ? `%${q}%` : null;
  const pool = getPool();

  if (searchPattern) {
    const contributorSearch = await pool.query<{ has_match: boolean }>(
      `
      SELECT EXISTS (
        SELECT 1
        FROM contributions
        WHERE contributor_name ILIKE $1
           OR contributor_email ILIKE $1
      ) AS has_match
    `,
      [searchPattern]
    );

    if (contributorSearch.rows[0]?.has_match) {
      const countResult = await pool.query<{ total: string }>(
        `
        SELECT COUNT(*) AS total
        FROM contributions c
        WHERE c.contributor_name ILIKE $1
           OR c.contributor_email ILIKE $1
      `,
        [searchPattern]
      );

      const rowsResult = await pool.query<AdminWordRow>(
        `
        SELECT
          w.id AS word_id,
          w.french,
          w.english,
          w.nufi_json,
          c.id AS contribution_id,
          c.language,
          c.translation,
          c.synonyms,
          c.contributor_name,
          c.contributor_email,
          c.notes,
          c.status,
          c.created_at
        FROM contributions c
        INNER JOIN predefined_words w ON w.id = c.word_id
        WHERE c.contributor_name ILIKE $1
           OR c.contributor_email ILIKE $1
        ORDER BY
          CASE
            WHEN c.status = 'pending' THEN 0
            WHEN c.status = 'rejected' THEN 1
            WHEN c.status = 'approved' THEN 2
            ELSE 3
          END,
          c.created_at DESC,
          c.id DESC
        LIMIT $2 OFFSET $3
      `,
        [searchPattern, limit, offset]
      );

      return { rows: rowsResult.rows, total: Number(countResult.rows[0]?.total ?? 0), limit, offset };
    }
  }

  const searchWhere = searchPattern
    ? `AND (
        w.search_text ILIKE $2
        OR c.translation ILIKE $2
        OR c.synonyms ILIKE $2
        OR c.contributor_name ILIKE $2
        OR c.contributor_email ILIKE $2
      )`
    : '';
  const params = searchPattern ? [language, searchPattern, limit, offset] : [language, limit, offset];
  const limitParam = searchPattern ? '$3' : '$2';
  const offsetParam = searchPattern ? '$4' : '$3';

  const countResult = await pool.query<{ total: string }>(
    `
    SELECT COUNT(*) AS total
    FROM predefined_words w
    LEFT JOIN LATERAL (
      SELECT translation, synonyms, contributor_name, contributor_email
      FROM contributions
      WHERE word_id = w.id AND language = $1
      ORDER BY created_at DESC, id DESC
      LIMIT 1
    ) c ON true
    WHERE 1 = 1
      ${searchWhere}
  `,
    searchPattern ? [language, searchPattern] : [language]
  );

  const rowsResult = await pool.query<AdminWordRow>(
    `
    SELECT
      w.id AS word_id,
      w.french,
      w.english,
      w.nufi_json,
      c.id AS contribution_id,
      c.language,
      c.translation,
      c.synonyms,
      c.contributor_name,
      c.contributor_email,
      c.notes,
      c.status,
      c.created_at
    FROM predefined_words w
    LEFT JOIN LATERAL (
      SELECT id, language, translation, synonyms, contributor_name, contributor_email, notes, status, created_at
      FROM contributions
      WHERE word_id = w.id AND language = $1
      ORDER BY created_at DESC, id DESC
      LIMIT 1
    ) c ON true
    WHERE 1 = 1
      ${searchWhere}
    ORDER BY
      CASE
        WHEN c.status = 'pending' THEN 0
        WHEN c.status = 'rejected' THEN 1
        WHEN c.status = 'approved' THEN 2
        WHEN c.id IS NULL THEN 3
        ELSE 4
      END,
      c.created_at DESC NULLS LAST,
      w.source_row ASC,
      w.id ASC
    LIMIT ${limitParam} OFFSET ${offsetParam}
  `,
    params
  );

  return { rows: rowsResult.rows, total: Number(countResult.rows[0]?.total ?? 0), limit, offset };
}

export async function upsertAdminWordContribution(input: {
  wordId: number;
  contributionId?: number | null;
  language: string;
  translation: string;
  synonyms: string;
  contributorName: string;
  notes: string;
  status: string;
}) {
  await ensureSchema();
  if (input.contributionId) {
    const result = await updateAdminContribution({
      id: input.contributionId,
      language: input.language,
      translation: input.translation,
      synonyms: input.synonyms,
      contributorName: input.contributorName,
      notes: input.notes,
      status: input.status,
    });
    return result?.id ?? null;
  }

  const result = await getPool().query<{ id: number }>(
    `
    INSERT INTO contributions (word_id, language, translation, synonyms, contributor_name, notes, status)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
    RETURNING id
  `,
    [
      input.wordId,
      input.language.trim(),
      input.translation.trim(),
      input.synonyms.trim(),
      input.contributorName.trim(),
      input.notes.trim(),
      input.status.trim(),
    ]
  );
  return result.rows[0]?.id ?? null;
}

export async function updateAdminContribution(input: {
  id: number;
  language: string;
  translation: string;
  synonyms: string;
  contributorName: string;
  notes: string;
  status: string;
}) {
  await ensureSchema();
  if (input.status.trim() === 'rejected') {
    const target = await getPool().query<{
      id: number;
      word_id: number;
      language: string;
      translation: string;
      synonyms: string;
    }>(
      `
      SELECT id, word_id, language, translation, synonyms
      FROM contributions
      WHERE id = $1
      LIMIT 1
    `,
      [input.id]
    );

    const row = target.rows[0];
    if (!row) return null;

    await getPool().query(
      `
      UPDATE contributions
      SET status = 'rejected'
      WHERE word_id = $1
        AND language = $2
        AND translation = $3
        AND synonyms = $4
    `,
      [row.word_id, row.language, row.translation, row.synonyms]
    );

    return { id: row.id };
  }

  const result = await getPool().query<{ id: number }>(
    `
    UPDATE contributions
    SET language = $2,
        translation = $3,
        synonyms = $4,
        contributor_name = $5,
        notes = $6,
        status = $7
    WHERE id = $1
    RETURNING id
  `,
    [
      input.id,
      input.language.trim(),
      input.translation.trim(),
      input.synonyms.trim(),
      input.contributorName.trim(),
      input.notes.trim(),
      input.status.trim(),
    ]
  );
  return result.rows[0] ?? null;
}

export async function approveAdminContributions(ids: number[]) {
  await ensureSchema();
  const uniqueIds = [...new Set(ids.filter((id) => Number.isInteger(id) && id > 0))];
  if (uniqueIds.length === 0) return 0;

  const result = await getPool().query(
    `
    UPDATE contributions
    SET status = 'approved'
    WHERE id = ANY($1::int[])
      AND status <> 'approved'
  `,
    [uniqueIds]
  );

  return result.rowCount ?? 0;
}

export async function rejectAdminContributions(ids: number[]) {
  await ensureSchema();
  const uniqueIds = [...new Set(ids.filter((id) => Number.isInteger(id) && id > 0))];
  if (uniqueIds.length === 0) return 0;

  const result = await getPool().query(
    `
    WITH targets AS (
      SELECT word_id, language, translation, synonyms
      FROM contributions
      WHERE id = ANY($1::int[])
    )
    UPDATE contributions c
    SET status = 'rejected'
    FROM targets t
    WHERE c.word_id = t.word_id
      AND c.language = t.language
      AND c.translation = t.translation
      AND c.synonyms = t.synonyms
      AND c.status <> 'rejected'
  `,
    [uniqueIds]
  );

  return result.rowCount ?? 0;
}

export async function deleteAdminContributions(ids: number[]) {
  await ensureSchema();
  const uniqueIds = [...new Set(ids.filter((id) => Number.isInteger(id) && id > 0))];
  if (uniqueIds.length === 0) return 0;

  const result = await getPool().query(
    `
    WITH targets AS (
      SELECT word_id, language, translation, synonyms
      FROM contributions
      WHERE id = ANY($1::int[])
    )
    DELETE FROM contributions c
    USING targets t
    WHERE c.word_id = t.word_id
      AND c.language = t.language
      AND c.translation = t.translation
      AND c.synonyms = t.synonyms
  `,
    [uniqueIds]
  );

  return result.rowCount ?? 0;
}

export async function deleteAdminContribution(id: number) {
  await ensureSchema();
  const target = await getPool().query<{
    word_id: number;
    language: string;
    translation: string;
    synonyms: string;
  }>(
    `
    SELECT word_id, language, translation, synonyms
    FROM contributions
    WHERE id = $1
    LIMIT 1
  `,
    [id]
  );

  const row = target.rows[0];
  if (!row) return false;

  const result = await getPool().query(
    `
    DELETE FROM contributions
    WHERE word_id = $1
      AND language = $2
      AND translation = $3
      AND synonyms = $4
  `,
    [row.word_id, row.language, row.translation, row.synonyms]
  );
  return (result.rowCount ?? 0) > 0;
}

export async function getAdminPasswordHash(email: string) {
  await ensureSchema();
  const result = await getPool().query<{ password_hash: string }>(
    `SELECT password_hash FROM admin_users WHERE email = $1 LIMIT 1`,
    [email.trim().toLowerCase()]
  );
  return result.rows[0]?.password_hash ?? null;
}

export async function setAdminPasswordHash(email: string, passwordHash: string) {
  await ensureSchema();
  await getPool().query(
    `
    INSERT INTO admin_users (email, password_hash)
    VALUES ($1, $2)
    ON CONFLICT (email)
    DO UPDATE SET password_hash = EXCLUDED.password_hash,
                  password_updated_at = now()
  `,
    [email.trim().toLowerCase(), passwordHash]
  );
}
